on:
  push:
    branches: master

name: lintr

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_dev("remotes")
        shell: Rscript {0}
      - name: Install dependencies2
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("lintr@github-actions")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Lint package
        run: lintr::lint_package()
        shell: Rscript {0}
