on: [push, pull_request]

name: Pandoc

jobs:
  pandoc:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v1
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.9.1'
      - run: |
          echo "# hi" | pandoc -t html
