on:
  push:
    branches: master

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
                  -e 'remotes::install_deps(dependencies = TRUE)'
                  -e 'remotes::install_github("jimhester/pkgdown@github-actions-deploy")'
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e "pkgdown:::deploy_local(remote_url = sprintf('https://x-access-token:%s@github.com/jimhester/r-actions-test.git', Sys.getenv('GITHUB_TOKEN')))"
