on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
           r-version: 'release'
      
      - name: Report R Version 
        run: |
          which R
          R --version
