on: [push, pull_request]

name: Continuous integration

jobs:
  macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        r: ['3.2', '3.3', '3.4', '3.5', '3.6', 'devel']
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install LaTeX
        run: Rscript -e "install.packages('tinytex')" -e "tinytex::install_tinytex()"
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"

  linux:
    runs-on: ubuntu-latest
    container: rstudio/r-base:3.6-xenial
    env:
      CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install LaTeX
        run: Rscript -e "install.packages('tinytex')" -e "tinytex::install_tinytex()"
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install LaTeX
        run: |
          Rscript -e "install.packages('tinytex')" -e "tinytex::install_tinytex()" \
                  -e "cat('::add-path::{%s}', tinytex::tinytex_root())"
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"
