on: [push, pull_request]

name: Continuous integration

jobs:
  CI:
    strategy:
      matrix:
        cfg:
        - { os: windows-latest, r: '3.x' }
        - { os: macOS-latest, r: '3.x' }
        - { os: macOS-latest, r: 'devel' }
        - { os: ubuntu-latest, r: '3.2' }
        - { os: ubuntu-latest, r: '3.3' }
        - { os: ubuntu-latest, r: '3.4' }
        - { os: ubuntu-latest, r: '3.5' }
        - { os: ubuntu-latest, r: '3.6' }
    if: contains(matrix.cfg.os, 'ubuntu')
    container: rstudio/r-base:${{ matrix.cfg.os }}-xenial
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@master
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"
